### ISSUE TITLE
[Compat] Onions cut with Aquaculture 2 knives produce no effect

### ISSUE THREAD

**Issue by QuercusFelis** [davidjjung/oniononion#4]
Aquaculture knives are missing the tags necessary to produce the effects from cutting onions.

Related mods installed:
- Farmer's delight [1.2.4]
- Blueprint [6.2.0]
- Overweight Farming [2.0.0]
- Aquaculture 2 [2.4.8]

![image](https://github.com/davidjjung/oniononion/assets/37717887/60f9adfe-3ddc-40c5-adde-32be2fcd46c2)
![image](https://github.com/davidjjung/oniononion/assets/37717887/95c1371f-b9e8-4020-9c2a-46d2013d97b3)

**Comment by davidjjung** [comment]
Oh, huh--I had no idea overweight onions could peeled on a cutting boards. I have it hardcoded to work if normal onions are being cut, or if overweight onions are being peeled directly in-world. I'll make an item tag for onion-ish items that'll trigger reactions when processed on the cutting board. Thanks for bringing this to my attention! I'll upload a patch in two weeks at the latest.
